<a href="https://colab.research.google.com/github/ayush2281/Machine-Learning-libraries-/blob/main/NumpyLib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nummpy- *Numerical Python*

Advantages of Numpy Arrays:


1.  Allow severals Mathmetical operations
2.  Faster Operation



In [ ]:
import numpy as np

List vs Numpy Time taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
import time

python_list = [i for i in range(10000)]

start_time = time.process_time()

python_list = [i+5 for i in python_list]

end_time = time.process_time()

print(end_time - start_time)

0.0010705710000000757


Time taken by Numpy

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = time.process_time()


np_array += 5    #np_array = np_array+5


end_time = time.process_time()
print(end_time - start_time)



0.00018536099999977296


Numpy Arrays

In [ ]:
# list
list1 = [1,9,8,4]
print(list1)
type(list1)

[1, 9, 8, 4]


list

In [ ]:
np_array = np.array([1,9,8,4])
print(np_array)
type(np_array)

[1 9 8 4]


numpy.ndarray

In [ ]:
# creating 1 dimention array
a = np.array([5,65,2,5])
print(a)

[ 5 65  2  5]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,6,8,10),(7,8,2,3)])
print(b)

[[ 1  6  8 10]
 [ 7  8  2  3]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(54,5,8,9,3,0),(9,9,5,2,5,0),(8,8,5,2,4,0)])
print(c)

[[54  5  8  9  3  0]
 [ 9  9  5  2  5  0]
 [ 8  8  5  2  4  0]]


In [ ]:
c.shape

(3, 6)

In [ ]:
d = np.array([(1,6,9,8),(8,9,4,2)],dtype=float)
print(d)

[[1. 6. 9. 8.]
 [8. 9. 4. 2.]]


lnitial Place holder in a numpy arrays

In [ ]:
# create numpy arrays of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create a identity matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)


[[0.44991496 0.58122665 0.52889058 0.12108283]
 [0.34814164 0.41366899 0.76214021 0.53893291]
 [0.91028608 0.06753018 0.38598478 0.66031962]]


In [ ]:
# random integer values arrays within a specific range
c = np.random.randint(10, 100, (3, 5))
print(c)

[[97 84 13 83 45]
 [21 74 37 18 54]
 [33 19 55 83 60]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a listn into numpy array
list3 = [2,0,9,0,5,2,0]

np_array = np.asarray(list3)
print(np_array)
type(np_array)


[2 0 9 0 5 2 0]


numpy.ndarray

Analysing numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[29 57 23 28 17]
 [55 89 65 79 60]
 [82 27 46 53 34]
 [38 35 59 15 47]
 [45 80 17 57 61]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of ele in the  array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathmatical Operation on a numpy array or np array

In [ ]:
list1 = [6,9,2,8,7]
list2 = [9,5,7,1,4] # concatnate or join 2 list
print(list1 + list2)

[6, 9, 2, 8, 7, 9, 5, 7, 1, 4]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)
print()

print(a+b)


[[9 4 3]
 [9 7 1]
 [7 0 5]]
[[11 19 15]
 [10 12 11]
 [19 15 11]]

[[20 23 18]
 [19 19 12]
 [26 15 16]]


In [ ]:
print(a-b)
print()
print(a/b)
print()
print(a*b)

[[ -2 -15 -12]
 [ -1  -5 -10]
 [-12 -15  -6]]

[[0.81818182 0.21052632 0.2       ]
 [0.9        0.58333333 0.09090909]
 [0.36842105 0.         0.45454545]]

[[ 99  76  45]
 [ 90  84  11]
 [133   0  55]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[ 0  9 12]
 [ 8  2  8]
 [ 6  5 13]]
[[19 10 18]
 [19 12 18]
 [15 10 17]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 19 30]
 [27 14 26]
 [21 15 30]]
[[-19  -1  -6]
 [-11 -10 -10]
 [ -9  -5  -4]]
[[  0  90 216]
 [152  24 144]
 [ 90  50 221]]
[[0.         0.9        0.66666667]
 [0.42105263 0.16666667 0.44444444]
 [0.4        0.5        0.76470588]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(3,2))
print(array)
print()
print(array.shape)

[[3 5]
 [9 6]
 [7 2]]

(3, 2)


In [ ]:
#Transpose of mat
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[3 9 7]
 [5 6 2]]
(2, 3)


In [ ]:
# other way to find transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 9 7]
 [5 6 2]]
(2, 3)


In [ ]:
# reshaping the array

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 6 0]
 [1 7 2]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 6]
 [0 1]
 [7 2]]
(3, 2)
